### ISSUE TITLE
LibreOffice 5 on Mac fails to match words found in wordlist.txt  when added to ...

### ISSUE THREAD

**Issue by rr0ss0rr** [Glutanimate/wordlist-medicalterms-en#2]
I created a custom local dictionary under Writing Aid and appended your list via:

cat wordlist.txt >> medicalterms-en.dic 

It's not recognizing any of the words.  

```
~/Library/Application Support/LibreOffice/4/user/wordbook$ head medicalterms-en.dic 
OOoUserDict1
lang: en-US
type: positive

---
11-dehydrocorticosterone
1,2:5,6-dibenzanthracene
1,25-dihydroxycholecalciferol
1,3-diphosphoglyceric
17a-hydroxyprogesterone
17-hydroxycorticosteroid
```

ie.  Uvulopalatopharyngoplasty Uzman are both flagged but catoptroscope was ok .. Do I need to do anything special because of the size of the file?

**Comment by glutanimate** [comment]
Hi,

I haven't used a custom LO dictionary in a while (having opted for the system-wide hunspell method long ago), but your dictionary file looks fine to me. The header is there and everything looks properly formatted. No clue why it wouldn't work. OS X should use unix line endings, so that shouldn't be an issue, either. 

Maybe LO5 is to blame? When I tested my LO custom dictionary I was still on 3.x. It could be that something has changed in the meantime. If it has, it must be a bug because I haven't been able to find any documentation on changes in the custom dictionary system.

I take it you've already tried restarting LO? One other thing you could try is to create a new custom dictionary and just put some obscure medical terminology or gibberish words in it, just to see if LO has trouble with manually edited custom dictionaries in general.

That's about all I can think of right now. Hope it helps.

**Comment by rr0ss0rr** [comment]
@Glutanimate .. Thanks .. I think I will follow your lead .. I should be able to take this list and add it to ~/Library/Spelling on the Mac and make it a System wide dictionary .. Thanks

**Comment by rr0ss0rr** [comment]
One other question .. What is the difference between this repository and Glutanimate/hunspell-en-med-glut ??

**Comment by glutanimate** [comment]
The other repo contains a hunspell dictionary, i.e. a system-wide dictionary file that's used on Ubuntu and other Linux operating systems.
